name: 👷 DevOps
description: CI/CD and other DevOps concerns e.g. Updating the build, code analysis, test, deploy, application monitoring etc.
title: "devops: "
labels: ["area: devops"]
projects: ["webjs-tech/3"]
body:
  - type: textarea
    attributes:
      label: Describe the DevOps request
      description: Please describe the specific DevOps improvement or change you would like to request.
      placeholder: We are experiencing slow build times in our CI pipeline, which is impacting our development cycle. We would like to request improvements to optimize the build process and reduce the overall build time.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution or changes
      description: Describe the solution or changes you suggest for the DevOps request. Provide any relevant information or considerations.
      placeholder: |
        We suggest the following changes to improve the build performance:
        - Investigate the possibility of parallelizing the build stages to run tasks concurrently.
        - Optimize build scripts and dependencies to reduce unnecessary overhead.
        - Consider caching dependencies and artifacts to speed up subsequent builds.
        - Evaluate the use of build agents with higher compute resources to handle the workload more efficiently.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the DevOps request here, such as related issues, discussions, or examples.
      placeholder: |
        We have noticed that the build times have been steadily increasing as our codebase grows. This issue has been discussed among the development team, and we believe it's crucial to address it to maintain productivity and efficiency.

        Related Issues:
        - Issue #123: Performance degradation in the CI pipeline
        - Issue #456: Investigate build caching options
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue requesting the same devops request.
          required: true
