name: 🔒 Report a Vulnerability
description: Report a security vulnerability in the project
title: "vulnerability: "
labels: ["type: security"]
projects: ["webjs-tech/3"]
body:
  - type: textarea
    attributes:
      label: Describe the vulnerability
      description: Please describe the security vulnerability you have identified in the project.
      placeholder: I have identified a Cross-Site Scripting (XSS) vulnerability in the user profile page of our application. The vulnerability allows an attacker to inject malicious scripts into the user profile fields, which get executed when viewed by other users.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce the vulnerability, including any specific inputs or configurations.
      placeholder: |
        To reproduce the vulnerability, follow these steps:
          
        1. Log in as a regular user.
        2. Go to your own user profile page.
        3. Edit any user profile field (e.g., "About Me") and inject the following payload: `<script>alert('XSS attack!')</script>`.
        4. Save the changes.
        5. Switch to another user account or log out.
        6. Visit the user profile page of the user whose profile you edited.
        7. The injected script will execute, displaying an alert box with the message "XSS attack!".
    validations:
      required: true
  - type: textarea
    attributes:
      label: Impact of the vulnerability
      description: Describe the potential impact or consequences of the vulnerability if exploited.
      placeholder: This vulnerability allows an attacker to execute arbitrary JavaScript code in the context of other users' browsers, potentially leading to session hijacking, data theft, or further exploitation of the application's functionality.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other relevant information related to the vulnerability, such as related issues, discussions.
      placeholder: |
        - Related Issue: #1234
        - Discussion: [Link to Discussion](https://github.com/webjs-tech/reserv-me/issues/5678)
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue requesting the same vulnerability.
          required: true
